### PR TITLE
[ fix ] compilation error

### PR DESCRIPTION
**Pull request by AD1024**
This will cause a compilation error while running Relay test

### CODE REVIEW

**Comment by slyubomirsky** [comment]
Is there a specific case where this causes problems? It would be nice to add a test. I have never seen any issues arise from this line and I wonder if it could have to do with the system's settings for the C++ compiler or something like that

**Comment by junrushao1994** [comment]
I assume this is due to the recent object protocol refactor?

**Comment by AD1024** [comment]
> Is there a specific case where this causes problems? It would be nice to add a test. I have never seen any issues arise from this line and I wonder if it could have to do with the system's settings for the C++ compiler or something like that

Specifically, running the test `gluon_rnns` will encounter this error.

Error message:
```
source.cc 51:44: error: only virtual member functions can be marked 'final'
```

Also, running the test in aot repo (tested with latest version of tvm) will also raise this error message.

**Comment by slyubomirsky** [comment]
I think this may have to do with your clang settings, since the repo's other tests are failing

**Comment by slyubomirsky** [comment]
We should figure out what the underlying cause is, i.e., why this compilation error happens for you but not for Marisa or me

**Comment by MarisaKirisame** [comment]
@junrushao1994 That was my initial assumption too.
However, upon closer looking, I think what happend is simply some compiler are stricter then other.
It seems like tvm use some kind of static reflection and overload, where I assume it is just override.
Regardless, 0: the code in tvm mainline do not have final, and it has nothing wrong to just keep the same style, and 1: node system refactoring is not done yet. From what I understand all the node boilerplate will be generated.

**Comment by MarisaKirisame** [comment]
@slyubomirsky can you make sure pipsqueak aot work on latest commit?

**Comment by slyubomirsky** [comment]
It uses the latest commit

**Comment by MarisaKirisame** [comment]
great. so I think @AD1024 's compiler is just stricter.

**Comment by slyubomirsky** [comment]
Okay glad to hear there may be a TVM-related reason for this

**Pull request merged**
